### ISSUE TITLE
Redis Backup

### ISSUE THREAD

**Issue by liam-lai** [meifamily/ptt-alertor#113]
2xx MB currently.

**Comment by dinos80152** [comment]
http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/backups.html#backups-constraints
> For Redis (cluster mode disabled) clusters, backup and restore are not supported on cache.t1.micro or cache.t2.* nodes. All other cache node types are supported

@liam-lai free tier is cache.t2.micro.. Sad..

**Comment by dinos80152** [comment]
using [node-redis-dump](https://github.com/jeremyfa/node-redis-dump) instead.
