### ISSUE TITLE
Migration AWS account

### ISSUE THREAD

**Issue by liam-lai** [meifamily/ptt-alertor#117]
* [x] write cloudformation to deploy service
  * [x] ec2
  * [x] ecs
  * [x] vpc
  * [x] elb
  * [x] elasticcache
  * [x] elasticsearch with lambda function
  * [x] logs
  * [x] cloudwatch
  * [x] sns
  * [x] acm
  * [x] s3
* [x] migrate s3 folders and files
* [x] migrate aws acm ssl certification
* [x] migrate redis db
* [x] DNS change
* [x] migrate elasticsearch and kibana setting
* [x] migrate lambda code
* [x] setting cloudwatch alarm
* [x] change travis ci aws key, s3 bucket name

**Comment by liam-lai** [comment]
redis db migration :
http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/backups-exporting.html
http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/backups-restoring.html

**Comment by dinos80152** [comment]
s3 migration
https://aws.amazon.com/tw/premiumsupport/knowledge-center/account-transfer-s3/

**Comment by dinos80152** [comment]
finish, cloud formation repo is
https://github.com/meifamily/aws-cloudformation

high five~ :)
