### ISSUE TITLE
[通知看板所有文章] 新增查詢內文

### ISSUE THREAD

**Issue by alan23273850** [meifamily/ptt-alertor#134]
不知道目前已經實作出來的查詢文章**標題**功能，例如：

新增 hardwaresale regexp:\\[賣/(台中|台北)/.*\\]?(RAM|ram)+.*

是否可以延伸成查詢文章**內容**呢？(目前好像沒此功能) 不急，有空再實作也沒關係。

或者是開發者們方便告訴我可以從哪裡著手試著去修改 code 呢？

我現在很有時間也可能可以自己實作看看！

(不過如果我另外那邊的 server 最後能實作出我要的功能的話，這個 request 就會 cancel 了)

**Comment by alan23273850** [comment]
目前暫時不需要此功能～

**Comment by dinos80152** [comment]
目前不會想追蹤到所有文章的內容哦，感謝你的提議！
