### ISSUE TITLE
Connect to Line Notify failed

### ISSUE THREAD

**Issue by johnnylai** [meifamily/ptt-alertor#172]
I cannot connect my line to the service. 

The error message is
```
連結 LINE Notify 失敗。
請至 Ptt Alertor LINE 主頁回報區留言。
```

I think the error comes from [this line](https://github.com/Ptt-Alertor/ptt-alertor/blob/master/channels/line/notify.go#L78)

**Comment by ghost** [comment]
There's a solution that works for me.
Delete the PttAlertor account and add it again via the QR code on its [website](https://pttalertor.dinolai.com/).

**Comment by johnnylai** [comment]
Thank you @yolkee it works!
